### ISSUE TITLE
Add constants for strings

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#10]
In order to get rid of having to type `themeDay`/`lightSwitch`, it would be good to have these constants inside a `module.exports` or similar file. This would reduce typing errors!

**Comment by galmeida125** [comment]
I can do it.

**Comment by galmeida125** [comment]
https://github.com/timrodz/vscode-light_switch/pull/11

**Comment by timrodz** [comment]
Closed via #11.

**Comment by galmeida125** [comment]
@timrodz could you approve this PR for hacktoberfest tracking please?
