### ISSUE TITLE
Discussion: Features & Enhancements

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#12]
Hi team!

If you have any features/enhancements you'd like to propose, this is the place to share them.

**Comment by curtisbowden** [comment]
Random ideas.. disregard if they're already in the issue list somewhere... or if they're not feasible.
- Clickable light switch icon pinned to gui somewhere
- Fade slider to fade between the two themes
- Trigger light switch based on ambient light if device has sensor

**Comment by timrodz** [comment]
Hi @curtisbowden, thanks for your great ideas! Here are my thoughts:

>     * Clickable light switch icon pinned to gui somewhere

👍  This would be great! Do you have any knowledge in this area?

>     * Fade slider to fade between the two themes

🚫  I'm not sure this is possible - Could be a possible investigation but I wouldn't have many hopes for it just now.

>     * Trigger light switch based on ambient light if device has sensor

💡  If we can access these values through the API, then by all means go for it!

**Comment by curtisbowden** [comment]
> Hi @curtisbowden, thanks for your great ideas! Here are my thoughts:
> 
> > ```
> > * Clickable light switch icon pinned to gui somewhere
> > ```
> 
> 👍 This would be great! Do you have any knowledge in this area?
> 
No knowledge yet, I'll have to do a bit of research.. but I suspect it shouldn't be too difficult.  How about you?

**Comment by timrodz** [comment]
> > Hi @curtisbowden, thanks for your great ideas! Here are my thoughts:
> > > ```
> > > * Clickable light switch icon pinned to gui somewhere
> > > ```
> > 
> > 
> > 👍 This would be great! Do you have any knowledge in this area?
> 
> No knowledge yet, I'll have to do a bit of research.. but I suspect it shouldn't be too difficult. How about you?

That's the spirit! I'm also quite new to the VS Code API - I'll have a look during the weekend :)

**Comment by Kadajett** [comment]
I'd be willing to take a look at the ambient light switch! You could fake it for now by doing a time based switched option as well.

**Comment by curtisbowden** [comment]
> I'd be willing to take a look at the ambient light switch! You could fake it for now by doing a time based switched option as well.

I'm curious to see how you tackle this!

**Comment by timrodz** [comment]
Hi @Kadajett, I'd be very interested in this too. So far, it currently checks between night/day times through user-specified hours :)

**Comment by Kadajett** [comment]
Chrome V8 has the light sensor api incoming supposedly. That's the gold standard. I am in vacation at the moment, but I can spike it if someone doesn't beat me to it

**Comment by WretchedDade** [comment]
Hi @curtisbowden @timrodz , I looked into having an item in the status bar and it was pretty straightforward to get a working example. When clicked it calls the toggleThemes command. Should I open a PR for it?

![image](https://user-images.githubusercontent.com/17183431/67136067-3f1f3b80-f1ef-11e9-8c29-213c3990dbb6.png)

**Comment by curtisbowden** [comment]
> Hi @curtisbowden @timrodz , I looked into having an item in the status bar and it was pretty straightforward to get a working example. When clicked it calls the toggleThemes command. Should I open a PR for it?
> 
> ![image](https://user-images.githubusercontent.com/17183431/67136067-3f1f3b80-f1ef-11e9-8c29-213c3990dbb6.png)

Nice work!  @WretchedDade it would be a shame if you didn't open a PR for it ;)

**Comment by timrodz** [comment]
That's awesome! Thanks @WretchedDade 😄 will be reviewing this later.
