### ISSUE TITLE
Feature: Add basic contribution guidelines

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#14]
It would be good to set up a basic contribution guide.

You can reference [Mozilla's documentation](https://mozillascience.github.io/working-open-workshop/contributing/) for more information 😄

**Comment by jeffsieu** [comment]
Can I have a go at this issue?

**Comment by timrodz** [comment]
Hi @jeffsieu, be my guest! 😄

**Comment by timrodz** [comment]
Thank you, @jeffsieu! You're a legend! 🎉
