### ISSUE TITLE
Assign checking interval to a variable

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#2]
Currently, `extension.ts::activate` uses a magic number for its interval. Ideally, it should be saved inside a constant variable.

```ts
setInterval((): void => {
    setTheme(context, canSwitchToNightTheme());
  }, 60 * 10 * 1000); // Interval here
```

**Comment by grigori-gru** [comment]
Hi! I'll do it

**Comment by timrodz** [comment]
Hey @grigori-gru, thanks for contributing! :)
