### ISSUE TITLE
Investigate how to publish this tool

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#21]
So far we've received awesome contributions — Woohoo!

The next step is: figuring out how to get it into the VS Code marketplace.

Does anyone have any experience with this?

Related readings:

- [Publishing Extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)
- [Bundling Extension](https://code.visualstudio.com/api/working-with-extensions/bundling-extension)
- [Continuous Integration (CI)](https://code.visualstudio.com/api/working-with-extensions/continuous-integration)

Regarding CI, I've seen many repos use [Travis CI](https://travis-ci.org/) as their go-to tool. Any thoughts on this?

**Comment by ashwinimanoj** [comment]
Hi, I would like to help with this although I haven't published a vscode extension before and haven't worked with TravisCI (I am familiar with TeamsCity, another CI tool).

**Comment by timrodz** [comment]
Hi @ashwinimanoj, awesome! Welcome aboard 🚢 Go for it 😄

**Comment by ashwinimanoj** [comment]
@timrodz, I am trying to add some tests before working on the publishing part, what would you like to add as `publisher` in `package.json`? For now, I have set it as `timrodz` but just wanted to check if you would like me to continue with that.

**Comment by timrodz** [comment]
That sounds good to me, @ashwinimanoj  😄

**Comment by ashwinimanoj** [comment]
@timrodz , it looks like Azure DevOps organisation is required to publish the extension to the marketplace, do you have one already or should we look into creating one?

**Comment by timrodz** [comment]
I'll have to create one. Are there any helper links you could provide please?

**Comment by ashwinimanoj** [comment]
@timrodz [This](https://docs.microsoft.com/en-gb/azure/devops/organizations/accounts/create-organization?view=azure-devops#create-an-organization) should get you started with creating a devops organisation. Once the organisation is created, [these](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) steps have to be followed to create a personal access token that can be used to publish the extension.

**Comment by timrodz** [comment]
Awesome, thank you! Will have a look later :)

**Comment by ashwinimanoj** [comment]
@timrodz , once you have created the organisation, add me to it! Thanks! :)

**Comment by timrodz** [comment]
Okay, should I use your account's email address?

**Comment by ashwinimanoj** [comment]
Yes that would be fine :)

**Comment by timrodz** [comment]
@ashwinimanoj Just sent you the invite!

**Comment by ashwinimanoj** [comment]
@timrodz Got it! :) Thank you!

**Comment by ashwinimanoj** [comment]
Hey just wanted to check, did you create the publisher `timrodz` on visual studio marketplace?

**Comment by timrodz** [comment]
Yep! I did it through the `vsce` [commands](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) :) haven't published it, though.

**Comment by ashwinimanoj** [comment]
Nice! :) Can you add me as a Contributor under the publisher from the [manage page](https://marketplace.visualstudio.com/manage/)?

**Comment by timrodz** [comment]
Hi @ashwinimanoj, I require an email under the hotmail domain in order for me to add you as a contributor. If you have one, feel free to send me the details via email.

**Comment by ashwinimanoj** [comment]
Hi, it looks like I won't be able to spend much time on this project. Sorry about that! Feel free to assign it to someone else. Thanks!

**Comment by timrodz** [comment]
Solved! The tool is now published: https://marketplace.visualstudio.com/items?itemName=timrodz.lightswitch
