### ISSUE TITLE
Add better screenshots / GIFs

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#4]
As of now, it can be a bit difficult to understand what this tool does. A set of new, clear screenshots and (better) GIFs would be great.

**Comment by galmeida125** [comment]
I can do it.

**Comment by timrodz** [comment]
Hi @galmeida125,

What ideas for visuals do you have in mind? 😄

**Comment by galmeida125** [comment]
I think that new screenshots can improve the understanding. I'm working on it.
