### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#5]
Currently, the suite of tests is very basic. Ideally, we should be testing the following areas:

- Utilities i.e. `workskpace`
- Commands i.e. `setTheme`, `switchThemes`
- Command binder - What could possibly go wrong?
- String verification through extension settings and `date`

If you have ideas for any other tests, let me know.

**Comment by galmeida125** [comment]
I can do it.

**Comment by timrodz** [comment]
Hi @galmeida125, go ahead! Thank you 😄 

Would be great if you could `star` this project as well 😉
