### ISSUE TITLE
Audit and improve util/workspace

### ISSUE THREAD

**Issue by timrodz** [timrodz/vscode-light-switch#6]
Currently, `workspace` runs methods with little to no checks. We should cover potential breaking cases such as:

- User having multi-root workspaces
- Themes that don't exist (or have been deleted)

**Comment by galmeida125** [comment]
I can do it.

**Comment by timrodz** [comment]
Hi @galmeida125,

Are there any improvements you could offer? I'd love to hear about them.

**Comment by timrodz** [comment]
Closed due to inactivity.
